# Modern configuration for multimodal disaster response
model:
  image_model: "resnet50"  # or "efficientnet-b0", "vit-base-patch16-224"
  text_model: "bert-base-uncased"  # or "distilbert-base-uncased", "roberta-base"
  fusion_method: "concatenation"  # or "attention", "bilinear"
  num_classes: 6
  dropout: 0.3

data:
  image_size: 224
  max_text_length: 128
  batch_size: 32
  num_workers: 4
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

training:
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.01
  scheduler: "cosine"
  warmup_steps: 1000
  gradient_clip: 1.0
  early_stopping_patience: 10

classes:
  - "damaged_infrastructure"
  - "damaged_nature" 
  - "fires"
  - "flood"
  - "human_damage"
  - "non_damage"

paths:
  data_dir: "data"
  output_dir: "outputs"
  model_dir: "models"
  logs_dir: "logs"